#pragma once
void error(char *msg);
void openinfile(char *fname);
void openoutfile(char *fname); 
void init(void);
int PROGRAM(void);
int OPT_DECLARATION(void);
int DECLARATION(void);
int ID_SEQUENCE(void);
int IDENTIFIER(void);
int STATEMENT(void);
int BLOCK(void);
int DECL_OR_ST(void);
int IO_STATEMENT(void);
int PRINTS_STATEMENT(void);
int PRINTN_STATEMENT(void);
int PRINT_STATEMENT(void);
int COND_STATEMENT(void);
int WHILE_STATEMENT(void);
int ASSIGN_STATEMENT(void);
int EXPRESSION(void);
int OPT_RHS(void);
int RHS_EQ(void);
int RHS_NEQ(void);
int SIGNED_TERM(void);
int PLUS_TERM(void);
int MINUS_TERM(void);
int TERM(void);
int STATEMENT(void);
int PRIMARY(void);
int EXPR1(void);
void error2(char *s1,char *s2);
void gettoken(void);
void get2(void);
char *subst(char *key);
int type(int c);
int match(char *s);
int id(char *name);
int number(char *name);
int string(char *name);
void enter(char *key,char *val);
int lookup(char *key);
void Remove(char *key);
int d(char *s1,char *s2,char *s3);